[package]
name = "server"
version = "1.0.0"
edition = "2021"

[dependencies]
log = "0.4.0"
actix-web = "4.0.1"
actix-session = "0.6.2"
env_logger = "0.9.0"
http = "0.2.6"
serde = { version = "1.0.136", features = ["derive"] }
diesel = { version = "1.4.8", features = ["postgres"] }
